name: iconsax
description: iconsax for flutter.
version: 1.0.0
homepage: https://iconsax.io/
repository: https://github.com/luisDanielRoviraContreras/flutter_iconsax
issue_tracker: https://github.com/luisDanielRoviraContreras/flutter_iconsax/issues
documentation: https://github.com/luisDanielRoviraContreras/flutter_iconsax

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: iconsax
      fonts:
        - asset: lib/assets/fonts/iconsax.ttf
  uses-material-design: true
